### ISSUE TITLE
Successive letters cannot decamelize correctly

### ISSUE THREAD

**Issue by JasinYip** [dsblv/decamelize-keys#2]
For example: `aBcDeDD` will been changed to `a_bc_de_dd`, but it should be `a_bc_de_d_d` isn't it? 😄

**Comment by dsblv** [comment]
Hi!

This is actually [a feature](https://github.com/sindresorhus/decamelize/issues/7) of "decamelize" library which is used by this module. 😏

Seems weird in your examples, but I think it's fair to consider multiple capital letters an abbreviation: `encodeURIComponent` becomes `encode_uri_component` and not `encode_u_r_i_component`.

**Comment by JasinYip** [comment]
You're right! 👍
